# Generated by Django 4.1.6 on 2023-03-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anunciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg', models.CharField(blank=True, max_length=80, null=True)),
                ('ter', models.CharField(blank=True, max_length=80, null=True)),
                ('qua', models.CharField(blank=True, max_length=80, null=True)),
                ('qui', models.CharField(blank=True, max_length=80, null=True)),
                ('sex', models.CharField(blank=True, max_length=80, null=True)),
                ('sab', models.CharField(blank=True, max_length=80, null=True)),
                ('dom', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens')),
                ('anunciante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.anunciante')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.horariofuncionamento')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('valor', models.FloatField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens')),
                ('anunciante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.anunciante')),
            ],
        ),
        migrations.AddField(
            model_name='anunciante',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.endereco'),
        ),
    ]
