# Generated by Django 4.1.6 on 2023-03-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
